# Generated by Django 6.0.3 on 2026-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image_url',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
