# Generated by Django 6.0.3 on 2026-06-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_winner_alter_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
