# Generated by Django 6.0.3 on 2026-06-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='watchlist_duplicate_prevention'),
        ),
    ]
