# Generated by Django 6.0.3 on 2026-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(max_length=256),
        ),
    ]
